### ISSUE TITLE
load_medley_metadata in medley/load.py

### ISSUE THREAD

**Issue by sai-soum** [sh-lee97/grafx-prune#1]
Hello,

Thank you for your work. I was trying to run an inference based on the code provided. Where did you get the pickle file for loudness metadata? I looked on the MedleyDB website but couldn't find it anywhere. Is there an algorithm that you use to generate this data and store it as a pickle file?

**Comment by sh-lee97** [comment]
Thanks for raising the issue!

Sorry for the inconvenience. The loudness metadata was initially used but is no longer used. We deleted that part in the latest commits. Also, we added the missing metadata (`correspondence.yaml` and `alignment.pickle`) of the Mixing Secrets (or Cambridge) dataset. You can find them in `data/mixing_secrets/metadata`, and the subdirectory structure inside the Mixing Secrets dataset should look like this:

``` bash
Zwiepack_Air/
├── Zwiepack_Air_Full
│   ├── 01_MainPair_DominantArray.wav
│   ├── 02_BassMic1_SpotMic.wav
│   ├── 03_BassMic2_PeerArray.wav
│   ├── 04_SaxMic1_SpotMic.wav
│   ├── 05_SaxMic2_PeerArray.wav
│   ├── 06_Room_Stereo.wav
│   ├── 07_Room_Mono1.wav
│   ├── 08_Room_Mono2.wav
│   └── Readme.txt
├── alignment.pickle
├── correspondence.yaml
└── mix.wav

```

Hope this resolves your issues.
